--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/SkyWars
build-by-default: true
branches:
- main
projects:
  SkyWars:
    path: ""
    libs: 
      - src: https://poggit.pmmp.io/ci/Infernus101/FormAPI/libFormAPI
...
