###########################################################################################
# This is a YML file. Be careful when editing. Check your edits in a YAML checker like    #
# the one at http://yaml-online-parser.appspot.com                                        #
###########################################################################################
---
# Config version node. Unique Config name.
# No reason to edit this
config-version: 5

# General in-game configuration.
general:
  # The game prefix. Which will be used for command sending, Messaging
  # And Console usage. Use `&` for `§`
  prefix: '§d[§eSkyWars§d] &a'
  # Join health for player when joining an arena.
  # If the health is greater than the player max health,
  # max health will be used instead.
  join-health: 20
  # Server default gamemode, you can choose what gamemode
  # your players will be in after leaving the match.
  default-gamemode: 0
  # Players can use varieties of commands, so make
  # Sure that player can use the command in game
  # and making sure that no cheat while in game.
  accepted-cmd: "leave:stats:kits"
  # Enable block statuses, it can be disabled if you do not want
  # this feature enabled.
  enable-block-status: false

# Database configuration for SkyWars.
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: database.db
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
...